platform :ios, '14.0'

# Use the React Native provided scripts
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'UserAuthenticationApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath]
  )

  target 'UserAuthenticationAppTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(installer)
    # Exclude arm64 for simulator on M1/M2
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
  end
end
